/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEW;



import MODEL.UserModel;
import UTILS.DB;
import UTILS.JTableModel;
import static VIEW.frmMain.ToplamHesap;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;


public class frmKullaniciEkle extends javax.swing.JFrame {

    /**
     * Creates new form frmKullaniciEkle
     */
    JTableModel xmodeltable;
     static int xSeciliId = 0;
     DB db;
     
    public frmKullaniciEkle() {
        initComponents();
        xSeciliId = 0;
        db=new DB();
       
        TabloOlustur();
         this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtsoyad = new javax.swing.JTextField();
        txtkulad = new javax.swing.JTextField();
        txtad = new javax.swing.JTextField();
        btnEkle = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtsifre = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableKullanici = new javax.swing.JTable();
        Temizle = new javax.swing.JButton();
        btnSil = new javax.swing.JButton();
        txtAra = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(51, 0, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        txtkulad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtkuladActionPerformed(evt);
            }
        });

        btnEkle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/Button-Add-icon.png"))); // NOI18N
        btnEkle.setText("Ekle/Güncelle");
        btnEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEkleActionPerformed(evt);
            }
        });

        jLabel1.setText("Ad");

        jLabel2.setText("Soyad");

        jLabel3.setText("Kullanici adı");

        jLabel4.setText("Sifre");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/new.png"))); // NOI18N
        jLabel5.setText("Kullanici ekleme İşlemleri");
        jLabel5.setToolTipText("");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel5.setMaximumSize(new java.awt.Dimension(90, 20));

        jTableKullanici.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableKullanici);

        Temizle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/refresh.png"))); // NOI18N
        Temizle.setText("Temizle");
        Temizle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TemizleActionPerformed(evt);
            }
        });

        btnSil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/delete.png"))); // NOI18N
        btnSil.setText("Sil");
        btnSil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSilActionPerformed(evt);
            }
        });

        txtAra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAraKeyPressed(evt);
            }
        });

        jLabel6.setText("ARANACAK KULLANICI ADI");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnEkle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Temizle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSil, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtsoyad, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                                .addComponent(txtkulad, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtsifre, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtad)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 133, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(txtAra, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(132, 132, 132))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtAra)
                        .addComponent(jLabel6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(txtad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel1))
                                                .addGap(18, 18, 18)
                                                .addComponent(txtsoyad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel2))
                                        .addGap(18, 18, 18)
                                        .addComponent(txtkulad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addComponent(txtsifre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4))
                        .addGap(27, 27, 27)
                        .addComponent(btnEkle, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSil, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(Temizle))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)))
                .addContainerGap(130, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEkleActionPerformed
       /*
        UserModel um=new UserModel();
        UserAdd ua=new UserAdd();
        um.name=txtad.getText();
        um.surname=txtsoyad.getText();
        um.username=txtkulad.getText();
        um.password=txtsifre.getText();
        try {
            
            
                 if (ua.KullaniciEkle(um)) {
                JOptionPane.showMessageDialog(null,"Başarıyla eklendi");
            }
            else{
                JOptionPane.showMessageDialog(null,"Başarısız");
            }
            
            
           
            
        } catch (SQLException ex) {
            Logger.getLogger(frmKullaniciEkle.class.getName()).log(Level.SEVERE, null, ex);
        }
        */
       
       UserModel am=new UserModel();
        
        
        
                am.name=txtad.getText();  
                am.surname=txtsoyad.getText();               
                am.username=txtkulad.getText();
                am.password=txtsifre.getText();
                
        
       
        KaydetGuncelleUser(xSeciliId,am);
        getUserListe();
       
        
    }//GEN-LAST:event_btnEkleActionPerformed

    
    void TabloOlustur(){
     xmodeltable=new JTableModel();
     jTableKullanici.setModel(xmodeltable);
     ListSelectionModel selectmodel =jTableKullanici.getSelectionModel();
 
      ListSelectionListener tableselect = new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                //JOptionPane.showMessageDialog(null, "Seçim Değişti");
                int id, rowindex;
                
                if (jTableKullanici.getSelectedRowCount() > 0)
                {
                    rowindex= jTableKullanici.getSelectedRow();                 

                    id = (int)jTableKullanici.getModel().getValueAt(rowindex, 0);
                    xSeciliId = id;
                    getKullanici(id);
                }
                
            }
        };  
        
        selectmodel.addListSelectionListener(tableselect);
 
 }
    
    
    
    
     void getKullanici(int xid){
 
      String sql = "select * from tblUser"
                + " Where userId = ? ";
       
        PreparedStatement pcmd; 
        ResultSet rs = null;
        
        try {
            if ((db.con == null) || (db.con.isClosed())) return;
            
            pcmd = db.con.prepareStatement(sql);  
            
            pcmd.setInt(1, xid);  
            
            rs = pcmd.executeQuery();            
            while (rs.next()){
                
                UserModel am=new UserModel();
                
                am.id=(rs.getInt("userId"));
                am.name=(rs.getString("Name"));
                am.surname=(rs.getString("SurName"));
                am.username=(rs.getString("UserName"));
                am.password=(rs.getString("Password"));
               
                                      
                txtad.setText(am.name);
                txtsoyad.setText(am.surname);
                txtkulad.setText(am.username);
                txtsifre.setText(am.password);
               
               
               
                xSeciliId = rs.getInt("userId");
                //MyModel.xliste.add(p);
            }
            rs.close();
            pcmd.close();
           
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Bilgiler Yüklenirken Hata Oldu: "+ e.getMessage());
        }  
     
 
     
 }
     
     
     void KaydetGuncelleUser(int xid,UserModel a){
  
      PreparedStatement  cmd;
       String sql;
        if (xid <= 0)            
            sql = "insert into  tblUser (Name,SurName,UserName,Password) values (?,?,?,?)  ";
            

        else
            sql = "Update tblUser set Name=?,SurName=?,UserName=?,Password=? "
            + " Where userId=? ";
            
        
           try {
               cmd = db.con.prepareStatement(sql);
               cmd.setString(1, a.name);
               cmd.setString(2, a.surname);
               cmd.setString(3, a.username);
               cmd.setString(4, a.password);
             
               if (xid > 0)
               cmd.setInt(5, xid);
               
               int Sonuc = cmd.executeUpdate();
               //JOptionPane.showMessageDialog(null, "Sonuç: " + Sonuc);
              JOptionPane.showMessageDialog(null, "Kaydet/Güncelle İşlemi başarılı: ");
               
               
           } catch (SQLException ex) {
              
               JOptionPane.showMessageDialog(null, "Kaydet/Güncelle İşleminde Hata: "+ ex.getMessage());
           } 
      
  
  }
    
    
     void getUserListe(){
       String sql = "select * from tblUser";
       
        PreparedStatement pcmd; 
        ResultSet rs = null;
        
        try {
            if ((db.con == null) || (db.con.isClosed())) return;
            
            pcmd = db.con.prepareStatement(sql);
            
         
            rs = pcmd.executeQuery();
            
            JTableModel.xliste.clear();
            
            while (rs.next()){
                UserModel am=new UserModel();
                am.id=(rs.getInt("userId"));
                am.name=(rs.getString("Name"));
                am.surname=(rs.getString("SurName"));
                am.username=(rs.getString("UserName"));
                am.password=(rs.getString("Password"));
                    
                JTableModel.xliste.add(am);
            }
            rs.close();
            pcmd.close();
            
            TabloOlustur();
            
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Bilgiler Yüklenirken Hata Oldu: "+ e.getMessage());
        }
      
      
  }
     
     
     
      void UserAra(String aranan){
        String sql = "select * from tblUser "+ " "
               + "Where Name like ? or Name like ? or Name like ? "
                + " order by Name ";
       
        PreparedStatement pcmd; 
        ResultSet rs = null;
        
        try {
            if ((db.con == null) || (db.con.isClosed())) return;
            
            pcmd = db.con.prepareStatement(sql);
            pcmd.setString(1, aranan);
            pcmd.setString(2, aranan + "%");
            pcmd.setString(3, "%"+aranan);
         
            rs = pcmd.executeQuery();
            
            JTableModel.xliste.clear();
            
            while (rs.next()){
                UserModel am=new UserModel();
                am.id=(rs.getInt("userId"));
                am.name=(rs.getString("Name"));
                am.surname=(rs.getString("SurName"));
                am.username=(rs.getString("UserName"));
                am.password=(rs.getString("Password"));
                    
                JTableModel.xliste.add(am);
            }
            rs.close();
            pcmd.close();
            
            TabloOlustur();
            
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Bilgiler Yüklenirken Hata Oldu: "+ e.getMessage());
        }
      
      
  }
     
     
     
     
    void userDelete(int xid){
 
      String sql = "delete  from tblUser where userId=?";
       
        PreparedStatement pcmd; 
       
        
        try {
            if ((db.con == null) || (db.con.isClosed())) return;
            
            pcmd = db.con.prepareStatement(sql);  
            
            pcmd.setInt(1, xid);  
            
             pcmd.executeUpdate();            
           
           
            pcmd.close();
           getUserListe();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Bilgiler Yüklenirken Hata Oldu: "+ e.getMessage());
        }  
     
 
     
 }
    
    
    
    private void txtkuladActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtkuladActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtkuladActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       
        getUserListe();
        
        
    }//GEN-LAST:event_formWindowOpened

    void temizle(){
         txtad.setText("");
        txtsoyad.setText("");
        txtkulad.setText("");
        txtsifre.setText("");
        xSeciliId=-1;
    }
    
    private void TemizleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TemizleActionPerformed
        
       temizle();
    
        
    }//GEN-LAST:event_TemizleActionPerformed

    private void btnSilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSilActionPerformed
       int cevap = JOptionPane.showConfirmDialog(null,"Silme işlemi geçekleşsinmi?","UYARI ", JOptionPane.YES_NO_OPTION);
        if (cevap==JOptionPane.YES_OPTION) {
            userDelete(xSeciliId);
       temizle();
        }
        
        
    }//GEN-LAST:event_btnSilActionPerformed

    private void txtAraKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAraKeyPressed
        UserAra(txtAra.getText());
    }//GEN-LAST:event_txtAraKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmKullaniciEkle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmKullaniciEkle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmKullaniciEkle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmKullaniciEkle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmKullaniciEkle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Temizle;
    private javax.swing.JButton btnEkle;
    private javax.swing.JButton btnSil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableKullanici;
    private javax.swing.JTextField txtAra;
    private javax.swing.JTextField txtad;
    private javax.swing.JTextField txtkulad;
    private javax.swing.JPasswordField txtsifre;
    private javax.swing.JTextField txtsoyad;
    // End of variables declaration//GEN-END:variables
}
