/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEW;

import BLL.AdisyonBLL;
import BLL.MasaBL;
import BLL.MenuBLL;
import MODEL.MasaModel;
import MODEL.UrunModel;
import UTILS.DB;
import UTILS.MyMasaPanel;
import UTILS.MyTableModel;
import UTILS.MyTreeModel;
import java.awt.Color;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.tree.DefaultMutableTreeNode;

/**
 *
 * @author LAB3-OGR
 */
public class frmMain extends javax.swing.JFrame {

    /**
     * Creates new form frmLogin
     */
    String User;
    Date dt;
    public static float sayac = 1;
    public static int HesapId = 0;
    UrunModel um = null;
    public static int SecilenMasaId = 0;
    AdisyonBLL abl = new AdisyonBLL();

    public frmMain(String user) {
        initComponents();
        User = user;
        //  this.setResizable(true);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jSplitPane2 = new javax.swing.JSplitPane();
        pnlMasa = new javax.swing.JPanel();
        pnlIslemler = new javax.swing.JPanel();
        pnlBilgi = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblTarih = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblKullanici = new javax.swing.JLabel();
        txtSecilenMasa = new javax.swing.JLabel();
        pnlSiparis = new javax.swing.JPanel();
        pnlHesap = new javax.swing.JPanel();
        btnMiktarArttir = new javax.swing.JButton();
        btnMiktarAzalt = new javax.swing.JButton();
        txtAdet = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtBirimFiyat = new javax.swing.JTextField();
        lblUrunAd = new javax.swing.JLabel();
        lblAdetTip = new javax.swing.JLabel();
        btnUrunEkle = new javax.swing.JButton();
        btnAdisyonUrunSil = new javax.swing.JButton();
        pnlMenü = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TreeMenu = new javax.swing.JTree();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lblSecilenMasa = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblSiparisÖzeti = new javax.swing.JTable();
        txtToplamFiyat = new javax.swing.JTextField();
        btnOde = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemMenü = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        chxMasaEkle = new javax.swing.JCheckBoxMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        Kulislem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ana Sayfa");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jSplitPane2.setDividerLocation(500);

        pnlMasa.setBackground(new java.awt.Color(204, 255, 255));
        pnlMasa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        pnlMasa.setForeground(new java.awt.Color(255, 255, 255));
        jSplitPane2.setLeftComponent(pnlMasa);

        pnlBilgi.setBackground(new java.awt.Color(204, 255, 255));
        pnlBilgi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel1.setBackground(new java.awt.Color(204, 0, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Tarih:");

        lblTarih.setText("jLabel2");

        jLabel2.setBackground(new java.awt.Color(204, 0, 0));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Kullanıcı:");

        lblKullanici.setText("jLabel3");

        txtSecilenMasa.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        javax.swing.GroupLayout pnlBilgiLayout = new javax.swing.GroupLayout(pnlBilgi);
        pnlBilgi.setLayout(pnlBilgiLayout);
        pnlBilgiLayout.setHorizontalGroup(
            pnlBilgiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBilgiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblKullanici)
                .addGap(168, 168, 168)
                .addComponent(txtSecilenMasa, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTarih)
                .addGap(19, 19, 19))
        );
        pnlBilgiLayout.setVerticalGroup(
            pnlBilgiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBilgiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBilgiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblTarih)
                    .addComponent(jLabel2)
                    .addComponent(lblKullanici)
                    .addComponent(txtSecilenMasa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlSiparis.setBackground(new java.awt.Color(204, 255, 255));
        pnlSiparis.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        pnlHesap.setBackground(new java.awt.Color(204, 255, 255));
        pnlHesap.setForeground(new java.awt.Color(204, 255, 255));

        btnMiktarArttir.setText("+");
        btnMiktarArttir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMiktarArttirActionPerformed(evt);
            }
        });

        btnMiktarAzalt.setText("-");
        btnMiktarAzalt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMiktarAzaltActionPerformed(evt);
            }
        });

        txtAdet.setEditable(false);
        txtAdet.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtAdet.setText("1.0");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Miktar:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Birim Fiyatı:");

        txtBirimFiyat.setEditable(false);

        lblUrunAd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblUrunAd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        btnUrunEkle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/Button-Add-icon.png"))); // NOI18N
        btnUrunEkle.setText("Ürünü Ekle");
        btnUrunEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUrunEkleActionPerformed(evt);
            }
        });

        btnAdisyonUrunSil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/delete.png"))); // NOI18N
        btnAdisyonUrunSil.setText("Adisyondan Sil");
        btnAdisyonUrunSil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdisyonUrunSilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlHesapLayout = new javax.swing.GroupLayout(pnlHesap);
        pnlHesap.setLayout(pnlHesapLayout);
        pnlHesapLayout.setHorizontalGroup(
            pnlHesapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHesapLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlHesapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblUrunAd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlHesapLayout.createSequentialGroup()
                        .addGroup(pnlHesapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(pnlHesapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnlHesapLayout.createSequentialGroup()
                                .addComponent(btnMiktarArttir)
                                .addGap(18, 18, 18)
                                .addComponent(btnMiktarAzalt))
                            .addGroup(pnlHesapLayout.createSequentialGroup()
                                .addComponent(txtAdet, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblAdetTip, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE))
                            .addComponent(txtBirimFiyat)
                            .addComponent(btnAdisyonUrunSil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnUrunEkle, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        pnlHesapLayout.setVerticalGroup(
            pnlHesapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHesapLayout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addComponent(lblUrunAd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlHesapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtBirimFiyat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlHesapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAdet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(lblAdetTip))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlHesapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMiktarArttir, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMiktarAzalt, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnUrunEkle, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAdisyonUrunSil, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnlMenü.setLayout(new java.awt.BorderLayout());

        TreeMenu.setBackground(new java.awt.Color(204, 255, 255));
        TreeMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TreeMenuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TreeMenu);

        pnlMenü.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setLayout(new java.awt.BorderLayout());

        lblSecilenMasa.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblSecilenMasa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        tblSiparisÖzeti.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblSiparisÖzeti.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSiparisÖzetiMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblSiparisÖzeti);

        txtToplamFiyat.setEditable(false);
        txtToplamFiyat.setText("0");

        btnOde.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/ode.png"))); // NOI18N
        btnOde.setText("Öde");
        btnOde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOdeActionPerformed(evt);
            }
        });

        jLabel6.setText("Toplam Fiyat:");

        javax.swing.GroupLayout pnlSiparisLayout = new javax.swing.GroupLayout(pnlSiparis);
        pnlSiparis.setLayout(pnlSiparisLayout);
        pnlSiparisLayout.setHorizontalGroup(
            pnlSiparisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSiparisLayout.createSequentialGroup()
                .addComponent(pnlMenü, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlSiparisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSiparisLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtToplamFiyat, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnOde, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlSiparisLayout.createSequentialGroup()
                        .addComponent(pnlHesap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlSiparisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE)
                            .addComponent(lblSecilenMasa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(381, 381, 381)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlSiparisLayout.setVerticalGroup(
            pnlSiparisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMenü, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlSiparisLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(124, 124, 124))
            .addGroup(pnlSiparisLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(pnlSiparisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSiparisLayout.createSequentialGroup()
                        .addComponent(pnlHesap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlSiparisLayout.createSequentialGroup()
                        .addComponent(lblSecilenMasa, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlSiparisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(pnlSiparisLayout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlSiparisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnOde)
                                    .addComponent(jLabel6)
                                    .addComponent(txtToplamFiyat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 126, Short.MAX_VALUE)))))
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlIslemlerLayout = new javax.swing.GroupLayout(pnlIslemler);
        pnlIslemler.setLayout(pnlIslemlerLayout);
        pnlIslemlerLayout.setHorizontalGroup(
            pnlIslemlerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlIslemlerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlIslemlerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlSiparis, javax.swing.GroupLayout.PREFERRED_SIZE, 999, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlBilgi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 94, Short.MAX_VALUE))
        );
        pnlIslemlerLayout.setVerticalGroup(
            pnlIslemlerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlIslemlerLayout.createSequentialGroup()
                .addComponent(pnlBilgi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlSiparis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jSplitPane2.setRightComponent(pnlIslemler);

        getContentPane().add(jSplitPane2, java.awt.BorderLayout.CENTER);

        jMenuBar1.setForeground(new java.awt.Color(204, 255, 255));

        jMenu1.setBackground(new java.awt.Color(204, 255, 255));
        jMenu1.setText("Menü");

        jMenuItemMenü.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemMenü.setText("Menü İşlemleri");
        jMenuItemMenü.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemMenüActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemMenü);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Masa ");

        chxMasaEkle.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        chxMasaEkle.setSelected(true);
        chxMasaEkle.setText("Masa Ekle");
        chxMasaEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chxMasaEkleActionPerformed(evt);
            }
        });
        jMenu3.add(chxMasaEkle);

        jMenuBar1.add(jMenu3);

        jMenu2.setText("Rapor");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Raporlama");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("Kullanıcı");

        Kulislem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_K, java.awt.event.InputEvent.CTRL_MASK));
        Kulislem.setText("Kullanıcı İşlemleri");
        Kulislem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KulislemActionPerformed(evt);
            }
        });
        jMenu4.add(Kulislem);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents
public static void TreeSetModel() {
        MenuBLL m = new MenuBLL();
        try {
            TreeMenu.setModel(MyTreeModel.CreateTree());

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }

    void UrunBilgileriTemizle() {
        HesapId = 0;
        btnAdisyonUrunSil.setVisible(false);
        btnUrunEkle.setText("Ürünü Ekle");
        um = null;
        lblUrunAd.setText("");
        lblAdetTip.setText("");
        txtAdet.setText("1");
        txtBirimFiyat.setText("");

    }
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        /*
        MasaBL mb = new MasaBL();
        try {
            mb.MasaGetir(pnlMasa);
        } catch (SQLException ex) {
            Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
         */
        btnAdisyonUrunSil.setVisible(false);
        MasaBL mb = new MasaBL();
        mb.loadMasa(pnlMasa);
        BilgiYükle();
        TreeSetModel();
        TableSetModel();

    }//GEN-LAST:event_formWindowOpened

    private void jMenuItemMenüActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMenüActionPerformed
        frmMenuIslemleri frm = new frmMenuIslemleri();
        frm.setVisible(true);
    }//GEN-LAST:event_jMenuItemMenüActionPerformed

    private void btnMiktarAzaltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMiktarAzaltActionPerformed
        if (lblAdetTip.getText().equals("")) {
            return;
        } else if (lblAdetTip.getText().equals("Porsiyon")) {
            if (sayac != 0.5) {
                sayac -= 0.5;

            }
        } else {
            if (sayac != 1) {
                sayac--;
            }

        }
        txtAdet.setText(sayac + "");
    }//GEN-LAST:event_btnMiktarAzaltActionPerformed

    private void btnMiktarArttirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMiktarArttirActionPerformed
        if (lblAdetTip.getText().equals("")) {
            return;
        } else if (lblAdetTip.getText().equals("Porsiyon")) {
            sayac += 0.5;
        } else {
            sayac++;
        }
        txtAdet.setText(sayac + "");
    }//GEN-LAST:event_btnMiktarArttirActionPerformed
    public static void TableSetModel() {
        try {
            String[] sutunlar = {"Hesap ID", "Ürün ID", "Ürün Adı", "Birim Fiyatı", "Adet", "Miktar", "Toplam"};
            AdisyonBLL abl = new AdisyonBLL();
            tblSiparisÖzeti.setModel(MyTableModel.resultSetToTableModel(abl.AdisyonGetir(SecilenMasaId), sutunlar));

            tblSiparisÖzeti.getColumnModel().getColumn(0).setMinWidth(0);
            tblSiparisÖzeti.getColumnModel().getColumn(0).setPreferredWidth(0);
            tblSiparisÖzeti.getColumnModel().getColumn(0).setMaxWidth(0);

            tblSiparisÖzeti.getColumnModel().getColumn(1).setMinWidth(0);
            tblSiparisÖzeti.getColumnModel().getColumn(1).setPreferredWidth(0);
            tblSiparisÖzeti.getColumnModel().getColumn(1).setMaxWidth(0);
            ToplamHesap();

        } catch (SQLException ex) {
            Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void btnOdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOdeActionPerformed
        MasaBL mbl = new MasaBL();
        MasaModel m = new MasaModel();
        m.masaId = SecilenMasaId;
        m.masaAdi = lblSecilenMasa.getText();
        m.dolu = false;
        try {
            if (SecilenMasaId != 0 && abl.AdisyonVarMı(SecilenMasaId)) {

                int cevap = JOptionPane.showConfirmDialog(null, m.masaAdi + " " + ToplamHesap() + "TL Ödensin Mi?", "Ödeme Yapılsın Mı?", JOptionPane.YES_NO_OPTION);
                if (cevap == JOptionPane.YES_OPTION) {
                    abl.AdisyonKapat((float) ToplamHesap(), m.masaId);
                    mbl.updateMasa(m);
                    mbl.clearAllMasa(pnlMasa);
                    mbl.loadMasa(pnlMasa);
                    TableSetModel();
                }
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Hata:" + ex.getMessage());
        }
    }//GEN-LAST:event_btnOdeActionPerformed

    private void TreeMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TreeMenuMouseClicked
        if (evt.getClickCount() == 2) {

            UrunBilgileriTemizle();
            DefaultMutableTreeNode node = (DefaultMutableTreeNode) TreeMenu.getLastSelectedPathComponent();
            Object nodeInfo = node.getUserObject();
            if (node.isLeaf()) {
                sayac = 1;
                txtAdet.setText(sayac + "");
                um = new UrunModel();
                um = (UrunModel) nodeInfo;
                lblUrunAd.setText(um.urunAdi);
                txtBirimFiyat.setText(String.valueOf(um.urunBirimFiyati));
                lblAdetTip.setText(um.miktarTipi);
            }
        }
    }//GEN-LAST:event_TreeMenuMouseClicked

    private void tblSiparisÖzetiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSiparisÖzetiMouseClicked
        btnAdisyonUrunSil.setVisible(true);
        int selectedIndex = tblSiparisÖzeti.getSelectedRow();
        btnUrunEkle.setText("Güncelle");
        um = new UrunModel();
        HesapId = (int) tblSiparisÖzeti.getValueAt(selectedIndex, 0);
        um.urunId = (int) tblSiparisÖzeti.getValueAt(selectedIndex, 1);
        um.urunAdi = tblSiparisÖzeti.getValueAt(selectedIndex, 2).toString();
        um.miktarTipi = (tblSiparisÖzeti.getValueAt(selectedIndex, 5).toString());

        lblUrunAd.setText(um.urunAdi);
        txtBirimFiyat.setText(tblSiparisÖzeti.getValueAt(selectedIndex, 3).toString());
        txtAdet.setText(tblSiparisÖzeti.getValueAt(selectedIndex, 4).toString());
        lblAdetTip.setText(um.miktarTipi);


    }//GEN-LAST:event_tblSiparisÖzetiMouseClicked

    private void chxMasaEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chxMasaEkleActionPerformed
        frmMasaDuzenle frm = new frmMasaDuzenle();
        frm.setVisible(true);
    }//GEN-LAST:event_chxMasaEkleActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        frmRapor rapor = new frmRapor();
        rapor.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void btnUrunEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUrunEkleActionPerformed
        try {
            if (SecilenMasaId == 0) {
                JOptionPane.showMessageDialog(null, "Lütfen ürün eklemek istediğiniz masayı seçiniz!");
            } else if (!(abl.AdisyonVarMı(SecilenMasaId))) {
                JOptionPane.showMessageDialog(null, "Seçtiğiniz masa da tanımlı bir adisyon yoktur.Masaya sağ tıklayarak adisyon açınız.");

            } else if (um == null) {
                JOptionPane.showMessageDialog(null, "Lütfen eklemek istediğiniz ürünü seçiniz!");

            } else {
                if (HesapId == 0) {

                    if (abl.AdisyonUrunEkle(SecilenMasaId, um, Float.parseFloat(txtAdet.getText()))) {
                        TableSetModel();
                        UrunBilgileriTemizle();
                    } else {
                        JOptionPane.showMessageDialog(null, "Ürün Eklenirken Hata Oluştu");

                    }
                } else {
                    um.urunBirimFiyati = Float.parseFloat(txtBirimFiyat.getText());
                    if (abl.AdisyonUrunGuncelle(HesapId, um, Float.parseFloat(txtAdet.getText()))) {

                        TableSetModel();
                        UrunBilgileriTemizle();

                    } else {
                        JOptionPane.showMessageDialog(null, "Ürün Güncellenirken Hata Oluştu");

                    }

                }
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Veri Tabanın da  Hata Oluştu.Hata Mesajı=" + ex.getMessage());
        }
    }//GEN-LAST:event_btnUrunEkleActionPerformed

    private void btnAdisyonUrunSilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdisyonUrunSilActionPerformed
        try {
            abl.AdisyonUrunSil(HesapId);
            HesapId = 0;
            btnUrunEkle.setText("Ürünü Ekle");
            UrunBilgileriTemizle();
            btnAdisyonUrunSil.setVisible(false);
            TableSetModel();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Veri Tabanın da Hata Oluştu" + ex.getMessage());
        }
    }//GEN-LAST:event_btnAdisyonUrunSilActionPerformed

    private void KulislemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KulislemActionPerformed
      
        frmKullaniciEkle frm=new frmKullaniciEkle();
        frm.setVisible(true);
        
        
    }//GEN-LAST:event_KulislemActionPerformed

    void BilgiYükle() {
        lblKullanici.setText(User);
        dt = new Date();
        SimpleDateFormat ft
                = new SimpleDateFormat("dd-MM-yyyy");
        lblTarih.setText(ft.format(dt));
    }

    public static double ToplamHesap() {
        double toplam = 0;
        if (tblSiparisÖzeti.getRowCount() != 0) {
            for (int i = 0; i < tblSiparisÖzeti.getRowCount(); i++) {

                toplam = toplam + (double) tblSiparisÖzeti.getValueAt(i, 6);
            }
        }
        txtToplamFiyat.setText(String.valueOf(toplam));

        return toplam;

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain("").setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Kulislem;
    public static javax.swing.JTree TreeMenu;
    private javax.swing.JButton btnAdisyonUrunSil;
    private javax.swing.JButton btnMiktarArttir;
    private javax.swing.JButton btnMiktarAzalt;
    private javax.swing.JButton btnOde;
    private javax.swing.JButton btnUrunEkle;
    private javax.swing.JCheckBoxMenuItem chxMasaEkle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItemMenü;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JLabel lblAdetTip;
    private javax.swing.JLabel lblKullanici;
    public static javax.swing.JLabel lblSecilenMasa;
    private javax.swing.JLabel lblTarih;
    private javax.swing.JLabel lblUrunAd;
    private javax.swing.JPanel pnlBilgi;
    private javax.swing.JPanel pnlHesap;
    private javax.swing.JPanel pnlIslemler;
    public static javax.swing.JPanel pnlMasa;
    private javax.swing.JPanel pnlMenü;
    private javax.swing.JPanel pnlSiparis;
    public static javax.swing.JTable tblSiparisÖzeti;
    private javax.swing.JTextField txtAdet;
    private javax.swing.JTextField txtBirimFiyat;
    private javax.swing.JLabel txtSecilenMasa;
    public static javax.swing.JTextField txtToplamFiyat;
    // End of variables declaration//GEN-END:variables
}
